### ISSUE TITLE
validation figure

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#103]
creating this as a place for discussion of the validation figure.

at the moment we have a substantial collection of metrics which each require explanation, although if we do most of it in the caption i don't think it will contribute to the overall word count

here's what we have at the moment
![validation_combined](https://user-images.githubusercontent.com/17133743/108216659-b7a64d00-7100-11eb-82b5-791fc8fd4f63.png)

do we want all 12 in the figure? if so, what order should they be in? i don't think we are near the ecology letters figure limit so it could feasibly be split into two.

**Comment by tpoisot** [comment]
we *definitely* do not want the 12 - I would go with three?

**Accuracy** - the predictions we make are likely to be ~ 85% correct and we do not overfit

**True positive** - the model is biased towards *under* predicting interactions, so it's likely to limit the number of spurious predictions

**TSS**: the TSS of 0.5, which is within the range of [this paper](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12103), but with fewer data required and a better accuracy

This seems like a simple figure to discuss *and* we also can compare this to another model using the same statistics.

**Comment by tpoisot** [comment]
Overall, the conclusion of this figure would be "The model works with a very limited amount of data (the network itself), it would probably work better if we integrate multiple data as we argue in this paper".

**Comment by gottacatchenall** [comment]
added a draft in #104

**Comment by tpoisot** [comment]
merged - do you want to add a paragraph of text + figure caption, and I'll edit it?

**Comment by gottacatchenall** [comment]
gave it a shot in #105
