### ISSUE TITLE
journal selection

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#107]
creating this as a place for conversation about journal selection /  a place to have different journal guidelines in one place

## Ecology Letters 
[**Ideas and Perspectives**](https://onlinelibrary.wiley.com/page/journal/14610248/homepage/forauthors.html) : 
>Ecology Letters is particularly interested in novel essays expressing new ideas and perspectives that will appeal to a wide ecological audience. It is important that Ideas and Perspectives be focused on a topic of current interest. We are interested in new ideas, emerging frameworks, and controversial perspectives on hot areas of research. There is a need to present a view that is sufficiently complete to convince reviewers of the value of the contribution. There is the same expectation for the novelty of Ideas and Perspectives as for Letters. Those articles principally reviewing a topic, those that are just as statement of opinion, and those primarily discussing the author's own work will not be considered. Articles that are successful usually present a quantitative analysis, as a way of introducing a new perspective in ecology. Authors interested in submitting such a manuscript should first send a one-paragraph proposal (no more than 300 words) to the Editorial Office (see above). 

**Word limit**: 7500
**Citation limit**: 
**Figure limit**: 10

Pros: 
Cons:

## Global Ecology and Biogeography

**Word limit**: 5000 (concepts), unknown (review)
**Citation limit**: 
**Figure limit**: 10

Pros: 
Cons:

> Concepts. These are papers that present and develop new ideas, conceptual syntheses, critiques of established ideas, etc. Typically these papers include at least preliminary empirical validation of the ideas discussed. Typically, there should not be more than 5000 words in the main body of the text, and 50 literature citations. Please use a structured Abstract, not longer than 250 words; 3-5 headings should be chosen to fit the structure of the paper. If you have an idea for a Concepts piece, please contact the Editor-in-chief before submitting.

>Research reviews. Reviews should strive to concisely and critically synthesize a subject, as opposed to being exhaustive. Please use a structured Abstract, not longer than 300 words: 3-5 headings should be chosen to fit the structure of the paper. If you have an idea for a Research review, please contact the Editor-in-chief before submitting.

## Royal Society Open Science
[**Review articles**](https://royalsocietypublishing.org/rsos/for-authors) :
> The journal welcomes unsolicited review proposals, but all proposals must first be agreed by the relevant Subject Editor. Proposals for reviews should be no longer than 1 side of A4, include a structural outline with sub-headings to briefly explain description of content, and must succinctly identify the core issue(s) to be addressed. Please note that reviews transferred from other Royal Society Publishing journals will not automatically be considered for publication; instead, before the review will be considered for publication in Royal Society Open Science, a proposal must be submitted for consideration and approved by the relevant Subject Editor. If you wish to propose a review, please ensure you have read, understood and follow our review proposal guidance. Please contact the Editorial Office with details of your proposal.

> Royal Society Open Science publishes high quality multidisciplinary of topics rich in novelty. There are currently two types of Review article being published:
> - Comprehensive reviews: an in-depth summary of the state-of-the-art in that field, exploring recent developments and their implications for the wider scientific community, highlighting new avenues for exploration in the field.
> - Mini-reviews: provide an introduction to topics in the field under evaluation with a generalist audience in mind. They can be more personal than a comprehensive review, but are not a summary of the author’s own work.

> Invited Perspectives are distinct from Reviews. They provides the reader with an overview of the subject and give a personal insight into the advances in the field and challenges the future may hold. Perspectives are only written by a Fellow or Foreign Member of the Royal Society.
The majority of reviews published in the journal are invited by the Editors. If you have an idea for a review, we ask that you follow the process below, as any submitted unsolicited review manuscripts will be unsubmitted by the editorial office and returned to the author(s). It will remain at the Editors’ discretion whether to invite a proposal from the authors of a submitted unsolicited review paper.

**Word limit**: 
**Citation limit**: 
**Figure limit**: 

Pros: 
Cons:

## Oikos 
[**Forum papers**](https://www.oikosjournal.org/authors/author-guidelines) :
> FORUM PAPERS are the home for synthesis and review. The format can be short notes or more substantial reviews to bring fields together, to transgress existing boundaries by synthesizing larger fields or seemingly disparate areas, and to offer new ways of interpreting existing data. Forum articles must strive for conceptual unification and serve as a point of departure for future work rather than just summarizing existing bodies of theory and data. It is an arena for challenging current thinking on ecological issues by revising established concepts and insights from critical experiments or for developing new theory to promote novel research. Purely speculative pieces are discouraged. Where uncertainties, problems, or debates in current theory are identified, authors are strongly encouraged to, wherever possible, highlight productive and positive lines of research that may resolve the issue. In particular, we encourage collaboration in debates to promote more effective synthesis and balance.  

**Word limit**: flexibl(?)
**Citation limit**: 
**Figure limit**: 

Pros: 
Cons:

## Ecography
[**Review and synthesis papers**](http://www.ecography.org/authors/author-guidelines) :
Review and synthesis papers provide a critical assessment of the literature with emphasis on current topics in which rapid and significant advances are occurring. Items in this category should be more focused than the broad, topical reviews typically published elsewhere, developing a synthesis that inspires new hypotheses or new methods. Contributions in this category will be solicited by the editors. However, unsolicited submissions will also be considered and sent for pre-submission assessment by Review & Synthesis editors. Review articles should be maximum 7500 words in length (main text) and maximum 10 figures, tables or boxes. 

**Word limit**: 7500
**Citation limit**: 
**Figure limit**: 

Pros: 
Cons:

**Comment by gottacatchenall** [comment]
personally Ecography's lede (A journal of space and time in ecology) makes me think it would fit well as an Ecography review, although i don't know anything about the editors there

**Comment by tpoisot** [comment]
I genuinely think this is a good paper, so let's aim as high as we can - ELE or GEB if we fit the word count. Roy Soc after that.
