### ISSUE TITLE
revision for philtransb submission

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#115]
a list of changes to be made

from the editor

- [x] intro paragraph on disease/host-parasites #117 
- [ ] more host-parasite references throughout 

feedback from people

- [x] address biases in data being compounded by models 
- [ ] there are some typos (#116 ...)
- [x] ~i want to add [this paper](https://www.biorxiv.org/content/biorxiv/early/2019/11/29/759944.full.pdf) and [this paper](https://onlinelibrary.wiley.com/doi/10.1111/ddi.13255) to the SDM section~ tried but they didn't fit well, so abandoning
- [x] Dom C's comments RE abstract
- [ ] Unreasonably vs reasonably - ln. 64
- [ ] Interaction strength section - possibly weave into argument of data sparsity and potential for predictive models
- [ ] 15 vs 16

**Comment by gottacatchenall** [comment]
also just to be clear is this the _Infectious disease macroecology: parasite diversity and dynamics across the globe_ issue?

**Comment by tpoisot** [comment]
yup, correct special issue

**Comment by tpoisot** [comment]
I've added a paragraph in 0199581d67a340f72b1c15024df48e00ad652920 about the circularity

**Comment by gottacatchenall** [comment]
now that #117 is merged, is there anything else we want to do before sending to coauthors prior to submission? @TanyaS08 @tpoisot

**Comment by tpoisot** [comment]
No, let's send to coauthors, we need to submit in 7 days.

**Comment by TanyaS08** [comment]
A suggestion based on Dom C's comment RE final sentence of abstract: Basically just axing a lot of redundant words - @tpoisot & @gottacatchenall 

We then provide a primer on the relevant methods and tools that will guide the development and integration of multiple sources of data and methodological approaches (including statistical, dynamical, and inferential models), sketching a path forward for this research program.

**Comment by gottacatchenall** [comment]
yeah thats good, the abstract is still < 200 words so any other changes to make it clearer are welcome

**Comment by gottacatchenall** [comment]
made this change to abstract in #119

**Comment by TanyaS08** [comment]
Okay 1) I think we keep al changes in #119 to keep things simple? 2) I've worked through most of Laura's comments and flagged others in the issue list
