### ISSUE TITLE
[reviewer one] inflating dataset with positive interactions clarification

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#122]
***Original reviewer comment***
> Lines 87-8: in addition, a claim is made that a slight inflation of positive interactions would overcome existing biases (in relation to imbalanced nature of the network). This needs to be described in more details, and qualified with evidence (e.g., sampling metrics), also a discussion must be made in relation to various subsampling/instance-synthesis techniques, and their effect on the predictions (as per above). Furthermore, clarification needs to be made if performance metrics were derived from the raw or the slightly inflated data.

**Comment by tpoisot** [comment]
This is where we can cite https://arxiv.org/abs/2105.14973 - we use an artificially balanced dataset for training; if we cite this, we don't have to justify the practice here.

**Comment by gottacatchenall** [comment]
this reference was just merged in #133
