### ISSUE TITLE
[reviewer one] preprints we cite

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#123]
***Original reviewer comment***
> Becker et al 2020: I am aware of this study and its limitations. Here, it is presented in the same way peer-reviewed studies are (see below), without discussing those limitations, particularly:
> 1) Study design – the overall performance of the final ensemble is significantly worse than some of components.
> 2) Lack of any quantification of uncertainties (e.g., as per discussion above).
>
> Overall, the authors cite only two pre-prints, to the exclusion of other pre-prints that could be useful in this discussion. Therefore, the authors must either: 1) justify why only those two preprints were used, 2) expand selection to include additional pre-prints; or > 3) remove these citations. Furthermore, there are few cases where the aforementioned work has been cited to the exclusion of other peer-reviewed work (e.g., in discussion of node-embedding: line 365).

**Comment by tpoisot** [comment]
this is a weird comment - I'll reply by saying that the reviewer has apparently not been able to identify other relevant preprints. That being said, we can add a caveat about the performance of the ensemble.

**Comment by TanyaS08** [comment]
@tpoisot will you add this response to the review doc? i.e. I'm tasking you with that

**Comment by tpoisot** [comment]
Yeah don't worry I'll work from the original reviews and make sure everything was addressed
