### ISSUE TITLE
[reviewer one] mention methods for using network structure to predict interactions 

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#124]
Combining these two ***original reviewer comments***

> How do we predict how species that we have never observed together will interact (355-374): there are other ways to incorporate network-structure into models to predict interactions within a given network, such as calculating network-based features, they need to be mentioned here for completeness.

> There are few other models that connect networks/their structures to predict interactions within the networks/subset of nodes in networks. They need to be sited here. (Lines 318-340)

**Comment by gottacatchenall** [comment]
this already occurs in the manuscript, and i added an additional mention

**Comment by TanyaS08** [comment]
@gottacatchenall can you clarify/adress this in review.md and then re-close?

**Comment by gottacatchenall** [comment]
@TanyaS08 think i've got this done now in #140
