### ISSUE TITLE
[reviewer one] More clear delineation of uni-,bi-,and k-partite networks

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#125]
***original reviewer comment***
> Interaction types: in general the authors allude to various types of interactions such as those present in food webs, and host-pathogen/parasite interactions. I think more could be made of these, in relation to uni-, bi- and k-partite networks, and type of interactions: for instance, in complex k-partite networks, network-based features might prove invaluable (because they can be computed to quantify indirect interactions in ways that other methods might not account for).

**Comment by tpoisot** [comment]
This is a strange comment - we can add a sentence very early in the manuscript saying that it works across multiple network types

**Comment by TanyaS08** [comment]
See commit `a19da207f79a89bd93254bed392c3580a193b572` although not sure if it best addresses the issue at hand (also warning for snarky comment in review doc that should be removed)
