### ISSUE TITLE
[reviewer one] More details on flow in networks

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#126]
***initial reviewer comment*** 
>  (Lines 375-397) This section could benefit from discussion of various types of flow in networks, for instance there are few examples in the literature (needs to be cited), were authors looked at the concept of flow in subtypes of ecological networks, and its meaning. Particularly for unipartite ecological networks – flow can be misleading in some scenarios, and very powerful in others.
In addition to interaction strength, weighted networks need to be mentioned somewhere, even if only for completeness.

**Comment by tpoisot** [comment]
this is _again_ a weird comment - weighted networks are interaction strength - we just need to drop a parenthesis saying that strength can represent flow, and add a few refs about flow like Montoya, Gaiarsa 2019, etc)

**Comment by TanyaS08** [comment]
I've clumsily started/tried to address this in the what is interaction strength section. I don't think it warrants a new paragraph?
