### ISSUE TITLE
Update the metadata.json file

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#13]
Please update your information in `metadata.json` ***in the order of this list***, then check your name

- [x] @TanyaS08 
- [x] @gottacatchenall  #15 
- [x] @FrancisBanville  #36 
- [x] @DominiqueCaron #37 
- [x] @gabrieldansereau  #44 
- [x] @Norma-Forero  #46 
- [x] @graciellehigino #51
- [x] @BenMerSci #52
- [x] **Laura**
- [x] @tpoisot

**Comment by tpoisot** [comment]
@FrancisBanville your turn!

**Comment by FrancisBanville** [comment]
There you go @tpoisot!

**Comment by tpoisot** [comment]
@DominiqueCaron your turn

**Please remember to use the following format for your branch**: `MISC/name-metadata`

**Comment by DominiqueCaron** [comment]
PR made.

@tpoisot @TanyaS08 to review before merging

**Comment by tpoisot** [comment]
Up next @gabrieldansereau

**Comment by gabrieldansereau** [comment]
PR #44 created @tpoisot @TanyaS08

**Comment by TanyaS08** [comment]
@Norma-Forero handing the baton over to you!

**Comment by gottacatchenall** [comment]
just a small note: it looks like both QCBS is written as both "Québec Centre for Biodiversity Sciences" and "Québec Centre for Biodiversity Science" in the json file and so both get rendered as unique affiliations on the html and pdf builds

**Comment by FrancisBanville** [comment]
Yeah you're right @gottacatchenall. And shouldn't it be spelled "Quebec Centre for Biodiversity Science", i.e. without the acute accent?

**Comment by gottacatchenall** [comment]
on the QCBS website it looks like the english doesn't include the accent and the french does, but i personally know very little in this realm so i'll defer to others

**Comment by tpoisot** [comment]
We can search and replace at the end, that's not an actual big deal.

**Comment by tpoisot** [comment]
@graciellehigino your turn!

**Comment by TanyaS08** [comment]
@BenMerSci your turn to give the deets

**Comment by tpoisot** [comment]
Let's close this one until @ljpollock joins the group - or @DominiqueCaron , can you add her infos?
