### ISSUE TITLE
Drop figure 1?

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#130]
What about dropping figure 1 entirely? We make it into a 2-panels with the loss curves on the left, and the imputed network on the right - the current one looks like a slide...

**Comment by gottacatchenall** [comment]
i think this is the right call, the only changes i would make to either figure as they are in #129 would be to have empirical and imputed interactions in different colors similar to in #127. thoughts @TanyaS08 ?

**Comment by TanyaS08** [comment]
Okay now that I've caught up with ALL the multiple streamsI'm good with that. I think it makes it easier to 'absorb' content-wise as well... To add onto Tim's analogy I feel like I need someone to 'decompose' the slide and walk me through it step-by-step so why not

**Comment by gottacatchenall** [comment]
here's a potential new fig 1 @tpoisot @TanyaS08 

![fig1](https://user-images.githubusercontent.com/17133743/122102104-134cc280-cde3-11eb-9999-1353cf04713f.png)

**Comment by tpoisot** [comment]
I like-ish it - maybe remove the fill and gather everything together?

**Comment by gottacatchenall** [comment]
yes need to mess with the padding options in plot layouts, also i can add lines from perfect/decent classifiers on this plot but it might make it hard to read

**Comment by gottacatchenall** [comment]
perhaps running many test/training splits and plotting a density of ROC/PRs to address the reviewer comment in #128 as well @tpoisot

**Comment by tpoisot** [comment]
Let me think about the confidence intervals a bit. I think we might want to split the figures in two. First the before/after networks, and then in the validation section, the two curves?
