### ISSUE TITLE
Figures update

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#31]
I think the figures should be on a transparent background - @gottacatchenall do you think this is an easy fix for you?

We also lack the forecasting figure.

**Comment by gottacatchenall** [comment]
i've added the forecasting figure in #32 --- i'll have a go at converting the conceptual fig to light-mode in the next few days, shouldn't be too hard

**Comment by tpoisot** [comment]
Closed by #32
