### ISSUE TITLE
The Glossary

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#39]
We have a few steps here:
 1. finalize the list of terms
 2. workshop definitions
 3. add to `manuscript.md` 

Proposed terms for glossary

1. Metaweb
2. Inference
3. Prediction
4. Forecasting
5. Hindcasting
6. Hyper-graphs
7. Machine learning
8. Supervised machine learning
9. Deep learning
10. Interactions
11. Network structure

**Comment by tpoisot** [comment]
I would maybe order them by "domain"?

### Network ecology
Species interactions
Network structure
Metaweb
Hyper-graphs
### Machine learning
Machine learning
Supervised machine learning
Deep learning
### Prediction
Inference
Prediction
Forecasting
Hindcasting
