### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#99]
https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13329

Can be used to support our claim that ML is likely to work (let's add it to the conclusion)

**Comment by gottacatchenall** [comment]
added in #100

**Comment by gottacatchenall** [comment]
[this paper](dx.doi.org10.1111/ele.13682) just out in letters seems it should be cited in the section on phylo matching

**Comment by tpoisot** [comment]
yup, go for it!
